-- RUN THIS FIRST IN CASE THERE STILL NO ROLE AND DROP DATABASE INSIDE psql
--      psql> create role spatu login password 'spatu' ;
--      psql> create database spatu owner spatu encoding 'UTF8';
--      psql> \c spatu;
--      psql> create extension postgis;


CREATE TABLE auth_assignment
(
    item_name  character varying(64) NOT NULL,
    user_id    integer               NOT NULL,
    created_at integer
);
ALTER TABLE auth_assignment
    OWNER TO spatu;

CREATE TABLE auth_item
(
    name        character varying(64) NOT NULL,
    type        integer               NOT NULL,
    description text,
    rule_name   character varying(64),
    data        text,
    created_at  integer,
    updated_at  integer
);
ALTER TABLE auth_item
    OWNER TO spatu;

CREATE TABLE auth_item_child
(
    parent character varying(64) NOT NULL,
    child  character varying(64) NOT NULL
);
ALTER TABLE auth_item_child
    OWNER TO spatu;

CREATE TABLE auth_rule
(
    name       character varying(64) NOT NULL,
    data       text,
    created_at integer,
    updated_at integer
);
ALTER TABLE auth_rule
    OWNER TO spatu;

CREATE TABLE migration
(
    version    character varying(180) NOT NULL,
    apply_time integer
);
ALTER TABLE migration
    OWNER TO spatu;

CREATE TABLE session
(
    id     character(64) NOT NULL,
    expire integer       NOT NULL,
    data   bytea         NOT NULL
);
ALTER TABLE session
    OWNER TO spatu;

CREATE TABLE "user"
(
    id                       integer GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME user_id_seq CACHE 1) primary key,
    username                 character varying(255) NOT NULL,
    email                    character varying(255) NOT NULL,
    password_hash            character varying(255) NOT NULL,
    status                   smallint               NOT NULL,
    auth_key                 character varying(32)  NOT NULL,
    password_reset_token     character varying(255),
    account_activation_token character varying(255),
    created_at               integer                NOT NULL,
    updated_at               integer                NOT NULL,
    opd_id                   integer
        constraint fk_user_opd_id_opd_id
            references opd
            on delete set null
);

ALTER TABLE "user"
    OWNER TO spatu;

CREATE TABLE frontend_counter_save
(
    save_name  character varying(10) NOT NULL,
    save_value integer               NOT NULL
);

ALTER TABLE frontend_counter_save
    OWNER TO spatu;

CREATE TABLE frontend_counter_users
(
    user_ip   character varying(255) PRIMARY KEY,
    user_time integer NOT NULL
);
ALTER TABLE frontend_counter_users
    OWNER TO spatu;

create table article
(
    id               integer GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME article_id_seq CACHE 1) primary key,
    user_id          integer      not null,
    title            varchar(255) not null,
    summary          text         not null,
    content          text         not null,
    status           integer      not null,
    category         integer      not null,
    article_image_id integer,
    slug             varchar(255),
    created_at       integer,
    updated_at       integer,
    created_by       integer,
    updated_by       integer
);
ALTER TABLE article
    OWNER TO spatu;

CREATE TABLE article_image
(
    id         integer GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME article_image_id_seq CACHE 1) primary key,
    picture    character varying(255),
    filename   character varying(255),
    created_at integer,
    updated_at integer,
    created_by integer,
    updated_by integer
);
ALTER TABLE article_image
    OWNER TO spatu;


CREATE TABLE urusan
(
    id         integer GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME urusan_id_seq CACHE 1) primary key,
    nama       character varying(255) NOT NULL,
    is_aktif   boolean DEFAULT TRUE,
    created_at integer,
    updated_at integer,
    created_by integer,
    updated_by integer
);
ALTER TABLE urusan
    OWNER TO spatu;

CREATE TABLE opd
(
    id         integer GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME opd_id_seq CACHE 1) primary key,
    nama       character varying(255) NOT NULL,
    is_aktif   boolean DEFAULT TRUE,
    created_at integer,
    updated_at integer,
    created_by integer,
    updated_by integer
);
ALTER TABLE opd
    OWNER TO spatu;

CREATE TABLE urusan_opd
(
    id         integer GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME urusan_opd_id_seq CACHE 1) primary key,
    urusan_id  integer not null,
    opd_id     integer not null,
    created_at integer,
    updated_at integer,
    created_by integer,
    updated_by integer,
    FOREIGN KEY (urusan_id) REFERENCES urusan (id) ON DELETE CASCADE,
    FOREIGN KEY (opd_id) REFERENCES opd (id) ON DELETE CASCADE
);
ALTER TABLE urusan_opd
    OWNER TO spatu;

CREATE TABLE peta_cetak
(
    id         integer GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME peta_cetak_id_seq CACHE 1) primary key,
    nama       character varying(255) NOT NULL,
    deskripsi  character varying(255),
    nama_file  character varying(255),
    opd_id     integer,
    created_at integer,
    updated_at integer,
    created_by integer,
    updated_by integer,
    FOREIGN KEY (opd_id) REFERENCES opd (id) ON DELETE SET NULL
);
ALTER TABLE peta_cetak
    OWNER TO spatu;

create table peta
(
    id                   integer GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME peta_id_seq CACHE 1) primary key,
    nama                 character varying(255) NOT NULL,
    deskripsi            character varying(255),
    default_on_frontpage boolean default null,
    nama_file            character varying(100),
    nama_tabel           character varying(100),
    versi_peta           integer,
    opd_id               integer,
    created_at           integer,
    updated_at           integer,
    created_by           integer,
    updated_by           integer,
    FOREIGN KEY (opd_id) REFERENCES opd (id) ON DELETE SET NULL
);

alter table peta
    owner to spatu;

create table minta_layanan
(
    id            integer GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME minta_layanan_id_seq CACHE 1) primary key,
    nama_pemohon  character varying(255)        NOT NULL,
    alamat        character varying(255),
    nik           character(16)                 NOT NULL,
    no_telepon    character varying(15),
    email         character varying(100) UNIQUE NOT NULL,
    nama_file_ktp character varying(255),
    permohonan    character varying(255)        NOT NULL,
    status        SMALLINT,
    created_at    integer,
    updated_at    integer,
    created_by    integer,
    updated_by    integer
);

ALTER TABLE minta_layanan
    OWNER TO spatu;

CREATE TABLE peta_jsondata
(
    peta_id      integer PRIMARY KEY,
    peta_version integer,
    jsondata     text
);
